# Generated by Django 4.1 on 2023-03-03 08:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('company_size', models.CharField(blank=True, choices=[('SIZE_1_10', '1-10 employees'), ('SIZE_11_50', '11-50 employees'), ('SIZE_51_200', '51-200 employees'), ('SIZE_201_500', '201-500 employees'), ('SIZE_501_1000', '501-1000 employees'), ('SIZE_1001_5000', '1001-5000 employees'), ('SIZE_5000_PLUS', '5000+ employees')], max_length=255)),
                ('high_concept', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the job vacancy/role', max_length=255)),
                ('slug', models.SlugField(help_text='slug of the job', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Link to the job vacancy')),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Full time'), ('contract', 'Contract'), ('internship', 'Internship'), ('cofounder', 'Cofounder')], help_text='Contract type: Part time or Full time', max_length=255)),
                ('remote', models.BooleanField(help_text='Is it allowed to work remotely')),
                ('location_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Locations of the job', size=None)),
                ('currency', models.CharField(blank=True, default='$', help_text='The currency of the salary', max_length=3)),
                ('salary', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, help_text='Salary')),
                ('equity', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, help_text='Salary')),
                ('company', models.ForeignKey(help_text='Company', on_delete=django.db.models.deletion.CASCADE, to='scrapper.company')),
            ],
        ),
    ]
