# Generated by Django 4.1 on 2023-03-04 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_company_high_concept_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='created_at',
            field=models.DateField(default=datetime.date.today, help_text='Posted at'),
        ),
    ]
