# Generated by Django 4.1 on 2023-03-07 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_searchterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='scrapped_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Scrapped at'),
        ),
    ]
